server:
  servlet:
    context-path: /
  port: 80
spring:
  profiles:
    active: dev,common
  datasource:
    driver-class-name: ${xwDriverClassName}
    url: ${xwUrl}
    username: ${xwUsername}
    password: ${xwPassword}
    type: ${xwType}
