server:
  servlet:
    context-path: /
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: lxt000205
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/static
filePath: F:\newFloder\JavaThree\cskaoyan-admin\static\
logging:
  file: spring.log
  level:
    com.cskaoyan.mall.mapper: debug
