server:
  servlet:
    context-path: /
  port: 80
spring:
  profiles:
    active: dev,common
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 111111
    type: com.alibaba.druid.pool.DruidDataSource
