server:
  servlet:
    context-path: /
  port: 80
spring:
  profiles:
    active: db
  datasource:
<<<<<<< HEAD
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
=======
<<<<<<< HEAD
    driver-class-name: ${xwDriverClassName}
    url: ${xwUrl}
    username: ${xwUsername}
    password: ${xwPassword}
    type: ${xwType}
=======
    driver-class-name: ${myDriverClassName}
    url: ${myUrl}
    username: ${myUsername}
    password: ${myPassword}
    type: ${myType}
  resources:
    static-locations: classpath:/static
filePath: F:\newFloder\JavaThree\cskaoyan-admin\static\
logging:
  file: spring.log
  level:
    com.cskaoyan.mall.mapper: debug
>>>>>>> 0afb6ebfa0be1866977b0b86766121d10dc59c8d
>>>>>>> 3d278f281c72bfca69d7cd3e52bbb3dd6c2ea2ba
